"""Initial migration with enhanced application system

Revision ID: 61d4e7b541af
Revises: 
Create Date: 2025-09-13 12:32:48.897554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d4e7b541af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_description', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('source', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('salary_range', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('location', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('applications', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'location')
    op.drop_column('applications', 'salary_range')
    op.drop_column('applications', 'source')
    op.drop_column('applications', 'job_description')
    # ### end Alembic commands ###